"use strict";
const assert=require("node:assert/strict"), S=require("../src/simulator.cjs"), P=require("../src/physical-preview.cjs"), blank=require("../src/blank-farm.cjs");
const raw=blank(1791388800);raw.farm.cash=0;
Object.assign(raw.farm.epic,{cheaper_contractors:5,bust_unions:5,transportation_lobbyist:10});
raw.farm.habs=[18,18,null,null];raw.farm.vehicles[0]={id:11,cars:3};raw.farm.vehicles[1]={id:11,cars:2};
const {s,c}=S.prepare(raw);
for(const [id,level] of Object.entries({hab_capacity1:8,wormhole_dampening:25,leafsprings:30,hover_upgrades:25,hyper_portalling:25})) s.r[S.RMAP[id]]=level;
const before=JSON.stringify({s,c});
const hab=P.describe(s,c,"hab",0,18);
assert.equal(hab.capacity,Math.ceil(600e6*1.4*1.5));
assert.equal(hab.cost,Math.floor(3.89347e32*.75));
const vehicle=P.describe(s,c,"vehicle",0,11);
assert.equal(vehicle.cars,3);
assert.ok(Math.abs(vehicle.capacity-833333.3333333334*3*2.5*2.25*2.25*1.5*3600)<1);
assert.equal(vehicle.cost,Math.floor(9.9e27*.75));
assert.ok(hab.seconds>0 && Number.isFinite(hab.seconds));
s.cash=vehicle.cost;assert.equal(P.describe(s,c,"vehicle",0,11).seconds,0);s.cash=0;
assert.equal(P.describe(s,c,"hab",0,0).capacity,350,"non-portals exclude wormhole bonus");
assert.equal(P.describe(s,c,"vehicle",2,11).cars,1,"new train uses one car");
assert.equal(JSON.stringify({s,c}),before,"previews never mutate solver state or history");
const empty=S.clone(s);empty.h.fill(null);empty.v.forEach(v=>v.id=null);
assert.equal(P.describe(empty,c,"hab",0,18).seconds,Infinity);
console.log("PASS physical preview current research, portal/hover/Hyperloop/epic factors, slot-specific duplicate prices, cash, zero income, cars and no mutation.");
